language: android
android:
  compenents:
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug

deploy:
  provider: releases
  api_key: "$TOKEN"
  file:
    - app/build/outputs/apk/debug/*.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true